name: NodeJS Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Set NPM token
      run: |
        npm config set _auth ${{ secrets.NPM_TOKEN }}
        npm config set registry https://rbcplatform.jfrog.io/rbcplatform/api/npm/npm-virtual
    - name: yarn install and test
      run: |
        yarn
        yarn test
      env:
        CI: true
